[package]
name = "sqlpage"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = { version = "0.6.0", features = ["any", "runtime-actix-rustls", "sqlite", "postgres", "mysql"] }
actix-web = { version = "4", features = ["rustls"] }
handlebars = "4.3.3"
log = "0.4.17"
env_logger = "0.9.0"
actix-files = "0.6.2"
futures-util = "0.3.21"
tokio = { version = "1.20.1", features = ["sync"] }
tokio-stream = "0.1.9"
anyhow = "1.0.58"
serde = "1.0.140"
serde_json = { version = "1.0.82", features = ["preserve_order"] }