[package]
name = "sqlpage"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = { version = "0.6.0", features = ["any", "runtime-actix-rustls", "sqlite", "postgres", "mysql"] }
actix-web = { version = "4", features = ["rustls"] }
handlebars = "5.0.0-beta.0"
log = "0.4.17"
env_logger = "0.10.0"
actix-files = "0.6.2"
futures-util = "0.3.21"
tokio = { version = "1.20.1", features = ["rt"] }
tokio-stream = "0.1.9"
anyhow = "1.0.58"
serde = "1.0.140"
serde_json = { version = "1.0.82", features = ["preserve_order"] }
lambda-web = { version = "0.2.0", features = ["actix4"], optional = true }
sqlparser = { version = "0.30", features = ["visitor"] }
async-stream = "0.3"
async-trait = "0.1.57"
async-recursion = "1.0.0"
include_dir = "0.7.2"
