services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:secret@postgres
  postgres:
    ports:
      - "5432:5432"
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret